// AUTO-GENERATED by scripts/sync-config.py — do not edit by hand
window.MSD_SHARED_CONFIG = {
  "scenarioId": "baseline",
  "ticksPerHour": 20.0,
  "operatingHoursPerDay": 24.0,
  "utilizationTarget": 0.85,
  "deviceBufferFraction": 0.1,
  "portsPerVehicle": 2,
  "simDefaults": {
    "numVehicles": 8,
    "totalDevices": 20,
    "numLoadingStations": 2,
    "numOffloadStations": 3,
    "missionsPerVehiclePerDay": 3.0,
    "missionDuration": 40,
    "processTime": 10
  },
  "durationsHours": {
    "mission": 2.0,
    "process": 0.5
  }
};
