#!/usr/bin/env python3
"""Generate js/shared-config.js from fixtures/baseline.yaml for the browser sim."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from analysis.config_loader import load_shared_config

DEFAULT_YAML = ROOT / "fixtures" / "baseline.yaml"
OUT = ROOT / "js" / "shared-config.js"


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser(description="Sync YAML baseline to browser config")
    parser.add_argument("--config", type=Path, default=DEFAULT_YAML)
    parser.add_argument("--out", type=Path, default=OUT)
    args = parser.parse_args()

    cfg = load_shared_config(args.config)
    payload = {
        "scenarioId": cfg.scenario_id,
        "ticksPerHour": cfg.ticks_per_hour,
        "operatingHoursPerDay": cfg.operating_hours_per_day,
        "utilizationTarget": cfg.utilization_target,
        "deviceBufferFraction": cfg.device_buffer_fraction,
        "portsPerVehicle": cfg.ports_per_vehicle,
        "modes": {
            "highDataVolume": cfg.high_data_volume_mode,
            "offloadFactor": cfg.offload_factor,
        },
        "simDefaults": {
            "numVehicles": cfg.vehicles,
            "totalDevices": cfg.device_pool,
            "numLoadingStations": cfg.loading_stations,
            "numOffloadStations": cfg.offload_stations,
            "missionsPerVehiclePerDay": cfg.missions_per_vehicle_per_day,
            "missionDuration": cfg.mission_duration_ticks,
            "loadTime": cfg.load_time_ticks,
            "offloadTime": cfg.offload_time_ticks,
            "highDataVolumeMode": cfg.high_data_volume_mode,
            "offloadFactor": cfg.offload_factor,
        },
        "durationsHours": {
            "mission": cfg.mission_duration_hours,
            "load": cfg.load_time_hours,
            "offload": cfg.offload_time_hours,
        },
    }

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        "// AUTO-GENERATED by scripts/sync-config.py — do not edit by hand\n"
        f"window.MSD_SHARED_CONFIG = {json.dumps(payload, indent=2)};\n",
        encoding="utf-8",
    )
    print(f"Wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
